language: java
jdk: oraclejdk8
sudo: false
script: "mvn clean package -Pdocker"

after_success:
if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    echo "This is a pull request. No deployment will be done."
    exit 0
fi
if [[ "$TRAVIS_BRANCH" != "master" ]]; then
    echo "Pushed on a branch other than master. No deployment will be done."
    exit 0
fi
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export APP_VERSION=1.0.0-SNAPSHOT
  - export REPO=finium/keycloak
  - export DOCKER_TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else if [ -n "$TRAVIS_TAG" ]; then echo $TRAVIS_TAG; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:$APP_VERSION $REPO:$DOCKER_TAG
  - docker push $REPO:$DOCKER_TAG
