language: java
sudo: false
script: "mvn clean package -Pdocker"

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=finium/keycloak
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO:1.0.0-SNAPSHOT $REPO:$TAG
  - docker push $REPO
